services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=prodaja'
      - 'POSTGRES_PASSWORD=andjela'
      - 'POSTGRES_USER=andj'
    ports:
      - '5632:5432'

  postgres-test:

    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=roba'
      - 'POSTGRES_PASSWORD=andjela'
      - 'POSTGRES_USER=andj'
    ports:
      - '5633:5432'


